name: MineHorseRacingPlugin
main: net.akaishi_teacher.mhr.Main
version: beta1.1.0
softdepend: [WorldEdit]
loadbefore: [WorldEdit]

commands:
 minehorseracing:
  description: Commands of MineHorseRacingPlugin.
  permission-message: ยง4You don't have permission.
 mhr:
  description: Commands of MineHorseRacingPlugin.
  permission-message: ยง4You don't have permission.
