name: MineHorseRacingPlugin
main: net.akaishi_teacher.mhr.Main
version: 1.0.1.1

commands:
 minehorseracing:
  description: Commands of MineHorseRacingPlugin.
  permission-message: ยง4You don't have permission.
 mhr:
  description: Commands of MineHorseRacingPlugin.
  permission-message: ยง4You don't have permission.
